# Makefile for the Linux device tree

obj-y			:= core.o sys.o bus.o dd.o \
			   driver.o class.o platform.o \
			   cpu.o firmware.o init.o map.o dmapool.o \
			   dma-mapping.o devres.o \
			   attribute_container.o transport_class.o
obj-y			+= power/




